package uno.anahata.ai.model.core;

/**
 * Defines the role of the entity that created a message.
 */
public enum Role {
    /** A message sent by the end-user. */
    USER,
    /** A message generated by the AI model. */
    MODEL,
    /** A message containing the results of a tool execution. */
    TOOL
}
